### ISSUE TITLE
Doesn't work on communities in a flow 

### ISSUE THREAD

**Issue by BetzalelC** [SFDC-Assets/DynamicFlowProgress#3]
![image](https://user-images.githubusercontent.com/92738537/154721374-8ce11a5d-26dd-4692-9dd3-14c41fe72d24.png)

**Comment by BetzalelC** [comment]
@egyptguy Did you get notified of this issue

**Comment by egyptguy** [comment]
> @egyptguy Did you get notified of this issue

Hello @BetzalelC @boutiqueorchard - thanks for reaching out and your patience.  For context, this is a Salesforce Labs component, so it is a volunteer-led open source project and not supported under your services agreement.

The component is meant to be used in both LEX and communities, and I've been able to use the sample flow in both UIs ([see a community example here](https://isvsi-14ddd2ecd93-170154c42a9.force.com/deletetestcenter/s/)). 
 No doubt it's not showing for you.  Is there anything you can tell me about your attempt, or about your specific environment - that might help?  Some questions I came up with to start:

- Have you tried fully clearing your browser cache?  Caching is one of the most common issues I come across when developing or working with new components.
- Are your users having issues seeing the whole flow or just the embedded component?
- Are you unable to see all versions of the progress indicator, or only a specific one?
- What happens when you add another custom component to the flow - is it visible?
- Is the component behaving as expected when used in a flow on an internal Lightning page (not community)?
- Do your users have issues seeing any other Aura components?  This is a very simple one - there's no Apex controller or object access required, so a reason for issues with this one don't immediately come to mind.
- What users can't see the component - is it limited to a community profile?  Can a system administrator see the component in the community?  Can other internal users see it in the community?  Are you attempting to view from the guest user profile?
- Do the users have the "Run Flows" permission enabled in their profiles?
- Did you install the managed (AppExchange) or unmanaged version?

**Comment by BetzalelC** [comment]
@egyptguy No worries at all, just noticed on another issue that you mentioned you didn't get notified, hence I asked you, really appreciate the component and any time you taking to help me solve it!
See inline answers
Have you tried fully clearing your browser cache? Caching is one of the most common issues I come across when developing or working with new components.
**Yes and tried from a different browser as well**
Are your users having issues seeing the whole flow or just the embedded component?
**Just this component**
Are you unable to see all versions of the progress indicator, or only a specific one?
**All**
What happens when you add another custom component to the flow - is it visible?
**Other LWC's in the same flow are working fine**
Is the component behaving as expected when used in a flow on an internal Lightning page (not community)?
**yes**
Do your users have issues seeing any other Aura components? This is a very simple one - there's no Apex controller or object access required, so a reason for issues with this one don't immediately come to mind.
**Other aura components workd**
What users can't see the component - is it limited to a community profile? Can a system administrator see the component in the community? Can other internal users see it in the community? Are you attempting to view from the guest user profile?
**System admin can't see it in the community either**
Do the users have the "Run Flows" permission enabled in their profiles?
**yes**
Did you install the managed (AppExchange) or unmanaged version?
**Managed**

**Comment by RebbePod** [comment]
Issue resolved by using a different site template

**Comment by RebbePod** [comment]
@egyptguy The issue has been fixed?

**Comment by egyptguy** [comment]
@RebbePod I have been unable to replicate the issue and was closing an inactive issue.  Skimming now, do you recall which template caused vs. solved the problem?  I'm conducting final testing now for an LWC version of the component.

**Comment by RebbePod** [comment]
@egyptguy I believe it was using the Customer Account Portal
