### ISSUE TITLE
Component does not support flow variable {!Flow.ActiveStages}

### ISSUE THREAD

**Issue by marieannewouters** [SFDC-Assets/DynamicFlowProgress#6]
My company installed this package, but now it appears the progress bar cannot be shown based on the flow variable {!Flow.ActiveStages}. Which is pity, as you cannot use the functionality of stages to dynamically "show/hide" stages.
A colleague of mine will adapt this probably tomorrow and create a PR for this.
If you can then check, approve and create a new package (with link), then we can adapt this in our CI/CD process for the creation of our scratches.

Thanks!

**Comment by Garywoo** [comment]
I would also have liked to see support for the native flow stages. [This other component](https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000EczujUAB&tab=e) I was using uses the `{!$Flow.CurrentStage}` and `{!$Flow.ActiveStages}` variables to set the progress indicator, however it has its own problems (UI bugs), which is why I was looking for an alternative.

**Comment by egyptguy** [comment]
I'm closing out this issue, as the documentation clearly indicates this component doesn't use the $Flow stages variables, but thank you for your feedback.
